version: '3.1'

services:
  
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: testapp
      POSTGRES_USER: testapp
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./dbinit/initial.sql:/docker-entrypoint-initdb.d/initial.sql